embed_type:
  default: user
  type: enum
  choices:
    - playlist
  description: "Select the embed type. From where you want to embed music."
sc_user_id:
  type: string
  default: ""
  description: "Soundcloud User ID. Fetch user songs."
sc_playlist_id:
  type: string
  default: ""
  description: "Soundcloud Playlist ID. Fetch a playlist."
music_player_icon:
  type: string
  default: "fab-soundcloud"
  description: "Add icon to music player button."
svg_icons: 
  default: "fab-soundcloud"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 5 icons used in this theme component"
